services:
  postgres:
    image: postgres:16-alpine
    container_name: jobmatch-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-jobmatch_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-jobmatch_password}
      POSTGRES_DB: ${POSTGRES_DB:-jobmatch_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./apps/backaned
      dockerfile: Dockerfile
    container_name: jobmatch-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-jobmatch_user}:${POSTGRES_PASSWORD:-jobmatch_password}@postgres:5432/${POSTGRES_DB:-jobmatch_db}?schema=public
      JWT_SECRET: ${JWT_SECRET}
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
      PORT: 4000
    depends_on:
      - postgres

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: jobmatch-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:4000/api}
      NODE_ENV: production
    depends_on:
      - backend

volumes:
  postgres_data:
